### ISSUE TITLE
404 not found error when building with powershell

### ISSUE THREAD

**Issue by james28909** [ViGEm/HidGuardian#6]
Not sure what to do, I am trying to block the controller input system wide and forward it to steam only. But after hiding the input, and selecting steam as the whitelist app, it does not forward input signals to steam, even after reboot.

This is where I had the idea that maybe the version of hidguardian I was using was outdated, and it is. Looks like there is a version that was updated about 10 months ago, the version I have is 3 year old or so. So I downloaded the code and try to build it in powershell, but immediately it says "404 not found".

<PS C:\Users\no0bz\Downloads\this\HidGuardian> .\build.ps1
Windows PowerShell 5.1.19041.1
Invoke-WebRequest : 404: Not Found
At C:\Users\no0bz\Downloads\this\HidGuardian\build.ps1:53 char:28
+ ... Version = $(Invoke-WebRequest -UseBasicParsing $DotNetReleasesUrl | C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand>

that is the exact error and I am not to sure what to do next. I am just SICK of windows using the input in the start menu. I wish I could just block the input to all windows start menu/settings and all UWP apps, but it is looking impossible. Any help would be extremely awesome :D

**Comment by nefarius** [comment]
The current master branch is highly experimental, unstable, will probably not even work and will be archived soon in favour of better solutions. 

That said, you can ignore the broken build scripts and try building via Visual Studio solution directly. Again, no guarantees that it will spit out anything useful, this project is a mess to be frank unfortunately.

As four your original intent, this is a tricky one because there is quite a few APIs and drivers and layers regarding input devices involved in recent Windows and the HG approach might not even work for you. The way HG works is fairly simple, it sits on top of gaming devices (except mice and keyboards) and denies processes who wanna access it (either directly or via DirectInput or HID-API) the open request, therefore "hiding" it. The Win32 sub-system has multiple ways to ship input requests around and if it's not a single process that is responsible for what you experience I'm afraid with this solution/approach you'll simply be out of luck.

Hope I could clarify a few things. Cheers.
